services:
  bycar-website:
    container_name: bycar-website
    build:
      context: .
      args:
      - NODE_ENV=${NODE_ENV-staging}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - API_URL=${API_URL}
      - CDN_URL=${CDN_URL}
    volumes:
      - ./.output:/app/.output
    networks:
      - proxy

networks:
  proxy:
    external: true
